### ISSUE TITLE
the css and js files missing

### ISSUE THREAD

**Issue by hhsadiq** [dragg/project-flyer#1]
Hi @dragg 

Can you add css and js files in public folder. Following files are referenced in layout.blade.php but are not present in public

/css/app.css
/css/libs.css
/js/libs.js

Thanks

**Comment by dragg** [comment]
Hi, hhsadiq
This files should generate from resources using gulp. You need install npm, elixir and gulp and then just call 'gulp' from command.

**Comment by hhsadiq** [comment]
Ok...Thanks
